server.port=8080
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
flask.service.url=https://adaptive-ds-assistant.onrender.com
spring.application.name=adaptive-ds-assistant
logging.level.com.abb.adaptive=DEBUG
